const { db } = require('../db/db');
const { v4: uuidv4 } = require('uuid');
const { AppError } = require('../middleware/errorHandler');
const githubSubmissionService = require('./githubSubmissionService');
const { awardSolve } = require('./gamificationService');

function listSubmissions({ user, question_id, status, review_status, page = 1, limit = 50 }) {
  const offset=(page-1)*limit; const where=[]; const params=[];
  if(user.role!=='admin'&&user.role!=='mentor'){where.push('s.user_id = ?');params.push(user.id);}
  if(question_id){where.push('s.question_id = ?');params.push(question_id);} if(status){where.push('s.status = ?');params.push(status);} if(review_status){where.push('s.review_status = ?');params.push(review_status);}
  const whereSql=where.length?`WHERE ${where.join(' AND ')}`:''; const total=db.prepare(`SELECT COUNT(*) total FROM submissions s ${whereSql}`).get(...params)?.total||0;
  const data=db.prepare(`SELECT s.*,q.title question_title,q.difficulty question_difficulty,q.points question_points,t.name topic_name,u.name user_name,u.email user_email,u.avatar_url user_avatar,rev.name reviewer_name FROM submissions s JOIN questions q ON s.question_id=q.id LEFT JOIN topics t ON q.topic_id=t.id JOIN users u ON s.user_id=u.id LEFT JOIN users rev ON s.reviewer_id=rev.id ${whereSql} ORDER BY s.updated_at DESC,s.created_at DESC LIMIT ? OFFSET ?`).all(...params,limit,offset);
  return {data,total,page:Number(page),limit:Number(limit)};
}

async function submitViaGithub({user_id,question_id,github_url,assignment_id}) { const snapshot=await githubSubmissionService.getRepositorySnapshot(github_url); const question=db.prepare('SELECT * FROM questions WHERE id=? AND is_active=1').get(question_id); if(!question) throw new AppError('Question not found',404,'NOT_FOUND'); const now=new Date().toISOString(); let submission=db.prepare('SELECT * FROM submissions WHERE user_id=? AND question_id=?').get(user_id,question_id); if(submission) db.prepare("UPDATE submissions SET submission_type='github',github_url=?,status='under_review',review_status='pending',attempted_at=COALESCE(attempted_at,?),updated_at=? WHERE id=?").run(snapshot.canonicalUrl,now,now,submission.id); else {const id=uuidv4();db.prepare("INSERT INTO submissions (id,user_id,question_id,assignment_id,submission_type,github_url,status,review_status,attempted_at,created_at,updated_at) VALUES (?,?,?,?,'github',?,'under_review','pending',?,?,?)").run(id,user_id,question_id,assignment_id||null,snapshot.canonicalUrl,now,now,now);submission={id};} db.prepare("UPDATE assignments SET status='under_review' WHERE user_id=? AND question_id=?").run(user_id,question_id); githubSubmissionService.recordSnapshot({id:uuidv4(),submissionId:submission.id,snapshot}); return {...db.prepare('SELECT * FROM submissions WHERE user_id=? AND question_id=?').get(user_id,question_id),github_commit_sha:snapshot.commitSha,github_commit_url:snapshot.commitUrl,github_default_branch:snapshot.defaultBranch}; }

function reviewSubmission({submission_id,reviewer_id,review_status,feedback,manual_score,manual_feedback}) {
  if(!['approved','changes_requested','rejected'].includes(review_status)) throw new AppError('Invalid review status',400,'VALIDATION_ERROR');
  const submission=db.prepare('SELECT * FROM submissions WHERE id=?').get(submission_id); if(!submission) throw new AppError('Submission not found',404,'NOT_FOUND');
  if(review_status==='changes_requested'&&(!feedback||!feedback.trim())) throw new AppError('Feedback is required when requesting changes',400,'VALIDATION_ERROR','feedback');
  const now=new Date().toISOString(); const normalizedManual=manual_score===null||manual_score===undefined?null:Number(manual_score); if(normalizedManual!==null&&(!Number.isFinite(normalizedManual)||normalizedManual<0||normalizedManual>100)) throw new AppError('manual_score must be between 0 and 100',400,'VALIDATION_ERROR','manual_score');
  const newStatus=review_status==='approved'?'approved':review_status==='changes_requested'?'changes_requested':'rejected'; const assignmentStatus=review_status==='approved'?'completed':review_status==='changes_requested'?'ongoing':'incomplete'; const solvedAt=review_status==='approved'?now:submission.solved_at;
  // Manual score is an explicit admin/mentor override. AI score remains separate for auditability.
  const finalScore=normalizedManual!==null?normalizedManual:(submission.ai_score!=null?Number(submission.ai_score):submission.final_score!=null?Number(submission.final_score):null);
  db.prepare(`UPDATE submissions SET status=?,review_status=?,feedback=?,reviewer_id=?,reviewed_at=?,solved_at=?,manual_score=?,manual_feedback=?,manual_reviewer_id=?,manual_reviewed_at=?,final_score=?,updated_at=? WHERE id=?`).run(newStatus,review_status,feedback?.trim()||null,reviewer_id,now,solvedAt,normalizedManual,manual_feedback?.trim()||null,normalizedManual!==null?reviewer_id:null,normalizedManual!==null?now:null,finalScore,now,submission_id);
  if(normalizedManual!==null) db.prepare('INSERT INTO submission_score_audit (id,submission_id,reviewer_id,previous_score,new_score,feedback) VALUES (?,?,?,?,?,?)').run(uuidv4(),submission_id,reviewer_id,submission.final_score??null,normalizedManual,manual_feedback?.trim()||feedback?.trim()||null);
  db.prepare('UPDATE assignments SET status=? WHERE user_id=? AND question_id=?').run(assignmentStatus,submission.user_id,submission.question_id);
  const question=db.prepare('SELECT * FROM questions WHERE id=?').get(submission.question_id); if(review_status==='approved'&&submission.review_status!=='approved') awardSolve(submission.user_id,submission.question_id,question?.points||20);
  db.prepare("INSERT INTO notifications (id,user_id,title,message,type,link) VALUES (?,?,?,?, 'mentor',?)").run(uuidv4(),submission.user_id,review_status==='approved'?'Submission Approved! 🎉':'Submission Reviewed',review_status==='approved'?`Your solution for "${question?.title}" was approved!${finalScore!=null?` Final score: ${finalScore}/100.`:''}`:`Review feedback on "${question?.title}": "${feedback||'Please review changes.'}"`,'/submissions');
  return db.prepare('SELECT * FROM submissions WHERE id=?').get(submission_id);
}

function updateSubmission({submission_id,question_id,user_id,status}) { let submission=submission_id?db.prepare('SELECT * FROM submissions WHERE id=?').get(submission_id):question_id?db.prepare('SELECT * FROM submissions WHERE user_id=? AND question_id=?').get(user_id,question_id):null; if(submission_id&&!submission) throw new AppError('Submission not found',404,'NOT_FOUND'); if(submission&&submission.user_id!==user_id) throw new AppError("Forbidden: Cannot update another user's submission",403,'FORBIDDEN'); const now=new Date().toISOString(); if(submission){const wasSolved=['solved','completed','approved'].includes(submission.status);let attemptedAt=submission.attempted_at,solvedAt=submission.solved_at;if(status==='attempted'&&!attemptedAt)attemptedAt=now;else if(status==='solved'||status==='completed'){if(!attemptedAt)attemptedAt=now;solvedAt=now;}else if(status==='not_started')solvedAt=null;db.prepare('UPDATE submissions SET status=?,attempted_at=?,solved_at=?,updated_at=? WHERE id=?').run(status,attemptedAt,solvedAt,now,submission.id);if(!wasSolved&&['solved','completed'].includes(status)){const q=db.prepare('SELECT points FROM questions WHERE id=?').get(submission.question_id);awardSolve(user_id,submission.question_id,q?.points||20);}return db.prepare('SELECT * FROM submissions WHERE id=?').get(submission.id);} if(!db.prepare('SELECT id FROM questions WHERE id=?').get(question_id))throw new AppError('Question not found',404,'NOT_FOUND');const id=uuidv4();let attemptedAt=null,solvedAt=null;if(status==='attempted')attemptedAt=now;else if(status==='solved'||status==='completed'){attemptedAt=now;solvedAt=now;}db.prepare('INSERT INTO submissions (id,user_id,question_id,status,attempted_at,solved_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run(id,user_id,question_id,status,attemptedAt,solvedAt,now,now);if(['solved','completed'].includes(status)){const q=db.prepare('SELECT points FROM questions WHERE id=?').get(question_id);awardSolve(user_id,question_id,q?.points||20);}return db.prepare('SELECT * FROM submissions WHERE id=?').get(id); }
function getGithubSnapshots(submissionId){return githubSubmissionService.listSnapshots(submissionId);}
module.exports={listSubmissions,submitViaGithub,reviewSubmission,updateSubmission,getGithubSnapshots};
