require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const { errorHandler } = require('./middleware/errorHandler');
const authRoutes = require('./routes/authRoutes');
const questionRoutes = require('./routes/questionRoutes');
const dailyQuestionRoutes = require('./routes/dailyQuestionRoutes');
const assignmentRoutes = require('./routes/assignmentRoutes');
const submissionRoutes = require('./routes/submissionRoutes');
const progressRoutes = require('./routes/progressRoutes');
const analyticsRoutes = require('./routes/analyticsRoutes');
const userRoutes = require('./routes/userRoutes');
const codeExecutionRoutes = require('./routes/codeExecutionRoutes');
const cohortRoutes = require('./routes/cohortRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const aiQuestionRoutes = require('./routes/aiQuestionRoutes');
const app = express();
app.use(helmet({crossOriginResourcePolicy:false}));
const allowedOrigins=['http://localhost:5173','http://127.0.0.1:5173','http://localhost:3000','http://127.0.0.1:3000','https://dsatracker.axly.in',process.env.CLIENT_ORIGIN].filter(Boolean);
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.includes(origin)||process.env.NODE_ENV!=='production')cb(null,true);else cb(new Error('CORS policy: Not allowed by origin'));},credentials:true}));
app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true}));
if(process.env.NODE_ENV!=='test') app.use(morgan('dev'));
app.get('/health',(req,res)=>res.status(200).json({status:'ok',timestamp:new Date().toISOString()}));
app.use('/api/v1/auth',authRoutes); app.use('/api/v1/questions',questionRoutes); app.use('/api/v1/daily-question',dailyQuestionRoutes); app.use('/api/v1/assignments',assignmentRoutes); app.use('/api/v1/submissions',submissionRoutes); app.use('/api/v1/progress',progressRoutes); app.use('/api/v1/analytics',analyticsRoutes); app.use('/api/v1/users',userRoutes); app.use('/api/v1/code',codeExecutionRoutes); app.use('/api/v1/cohorts',cohortRoutes); app.use('/api/v1/notifications',notificationRoutes); app.use('/api/v1/ai-questions',aiQuestionRoutes);
app.use((req,res)=>res.status(404).json({error:{code:'NOT_FOUND',message:`Cannot ${req.method} ${req.originalUrl}`}}));
app.use(errorHandler); module.exports=app;
