const express = require('express');
const router = express.Router();
const {getSubmissions,submitViaGithub,reviewSubmission,aiReviewSubmission,updateSubmission,upsertQuestionSubmission,abandonSubmission}=require('../controllers/submissionController');
const {authenticate}=require('../middleware/auth');
const {requireRole}=require('../middleware/rbac');
const {validateBody}=require('../middleware/validator');
const {updateSubmissionSchema,githubSubmissionSchema,reviewSubmissionSchema}=require('../validation/schemas');
router.use(authenticate);
router.get('/',getSubmissions);
router.post('/github',validateBody(githubSubmissionSchema),submitViaGithub);
router.post('/:id/ai-review',requireRole('admin','mentor'),aiReviewSubmission);
router.post('/:id/review',requireRole('admin','mentor'),validateBody(reviewSubmissionSchema),reviewSubmission);
router.post('/',upsertQuestionSubmission);
router.post('/toggle',upsertQuestionSubmission);
router.patch('/:id',validateBody(updateSubmissionSchema),updateSubmission);
router.post('/:id/abandon',abandonSubmission);
module.exports=router;
