import React, { useState, useEffect } from 'react';
import { Trophy, Flame, Crown, CalendarDays } from 'lucide-react';
import { api } from '../services/api';

export default function Leaderboard({ currentUser }) {
  const [leaders,setLeaders]=useState([]), [loading,setLoading]=useState(true), [period,setPeriod]=useState('all');
  useEffect(()=>{loadLeaderboard();},[period]);
  async function loadLeaderboard(){setLoading(true);try{const res=await api.getLeaderboard(period);setLeaders(res.data||[]);}catch(e){console.error(e);setLeaders([]);}finally{setLoading(false);}}
  const labels={all:'All Time',weekly:'This Week',monthly:'This Month'};
  return <div className="space-y-6 max-w-5xl mx-auto">
    <div className="p-6 md:p-8 rounded-3xl bg-gradient-to-r from-[#0C1425] via-[#152042] to-[#0C1425] border border-cyan-900/30 shadow-2xl text-center space-y-3">
      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400 text-xs font-semibold"><Trophy className="w-3.5 h-3.5"/> <span>Axly Rankings</span></div>
      <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight">Leaderboard</h1>
      <p className="text-xs text-slate-400 max-w-xl mx-auto">Compete, solve challenges, build your streak and climb the rankings.</p>
    </div>
    <div className="flex justify-center"><div className="inline-flex p-1 rounded-xl bg-slate-900 border border-slate-800 gap-1">{Object.entries(labels).map(([key,label])=><button key={key} onClick={()=>setPeriod(key)} className={`px-4 py-2 rounded-lg text-sm font-semibold transition ${period===key?'bg-cyan-500/15 text-cyan-300 border border-cyan-500/30':'text-slate-400 hover:text-white'}`}><CalendarDays className="inline w-4 h-4 mr-1"/>{label}</button>)}</div></div>
    {!loading&&leaders.length>=3&&<div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
      {[1,0,2].map((idx,pos)=><div key={idx} className={`p-5 rounded-2xl bg-gradient-to-b from-slate-900/90 to-slate-950 flex flex-col items-center text-center space-y-3 ${idx===0?'border-2 border-amber-500/50 shadow-2xl shadow-amber-500/10 -translate-y-2':'border border-slate-700/60'}`}>
        {idx===0?<Crown className="w-7 h-7 text-amber-400 fill-amber-400"/>:<div className="w-8 h-8 rounded-full bg-white/10 text-slate-300 font-extrabold flex items-center justify-center text-xs">#{idx+1}</div>}
        <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-cyan-600 to-indigo-600 flex items-center justify-center text-xl font-bold text-white">{leaders[idx]?.name?.[0]?.toUpperCase()||'U'}</div>
        <div><div className="text-sm font-bold text-white">{leaders[idx]?.name}</div><div className="text-[11px] text-slate-400">{leaders[idx]?.institution||'Student'}</div></div>
        <div className="text-sm font-extrabold text-cyan-400">{leaders[idx]?.points||0} pts</div>
      </div>)}</div>}
    <div className="rounded-2xl bg-slate-900/70 border border-slate-800 overflow-hidden shadow-xl"><div className="px-5 py-4 border-b border-slate-800 flex items-center justify-between"><div className="text-sm font-bold text-white">{labels[period]} Rankings</div><div className="text-xs text-slate-500">Top 100 learners</div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs text-slate-300"><thead className="bg-slate-950/80 border-b border-slate-800 text-[11px] font-bold text-slate-400 uppercase tracking-wider"><tr><th className="px-6 py-4">Rank</th><th className="px-6 py-4">Developer</th><th className="px-6 py-4">Institution</th><th className="px-6 py-4 text-center">Completed</th><th className="px-6 py-4 text-center">Streak</th><th className="px-6 py-4 text-right">Points</th></tr></thead><tbody className="divide-y divide-slate-800/60">{loading?<tr><td colSpan={6} className="px-6 py-8 text-center text-slate-500">Loading rankings...</td></tr>:leaders.length===0?<tr><td colSpan={6} className="px-6 py-10 text-center text-slate-500">No ranking activity for this period yet.</td></tr>:leaders.map((user,idx)=>{const isCurrent=currentUser?.id===user.id;return <tr key={user.id} className={isCurrent?'bg-cyan-950/30 border-l-4 border-l-cyan-500':'hover:bg-white/[0.03]'}><td className="px-6 py-4 font-bold">{idx<3?['🥇','🥈','🥉'][idx]:`#${idx+1}`}</td><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-cyan-600 to-indigo-600 flex items-center justify-center font-bold text-white text-xs">{user.name?.[0]?.toUpperCase()||'U'}</div><div><div className="font-bold text-white">{user.name} {isCurrent&&<span className="text-[9px] px-1.5 py-0.5 rounded bg-cyan-500/20 text-cyan-400">YOU</span>}</div><div className="text-[10px] text-slate-500 font-mono">{user.email}</div></div></div></td><td className="px-6 py-4 text-slate-400">{user.institution||'Axly Academy'}</td><td className="px-6 py-4 text-center font-semibold text-emerald-400">{user.completed_count||0}</td><td className="px-6 py-4 text-center"><span className="inline-flex items-center gap-1 font-semibold text-amber-400"><Flame className="w-3.5 h-3.5 fill-amber-400"/>{user.streak||0}d</span></td><td className="px-6 py-4 text-right font-extrabold text-cyan-400">{user.points||0}</td></tr>})}</tbody></table></div></div>
  </div>;
}
